server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/springdb}
      username: postgres
      password: password
auth:
  jwt:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN
    secret: loksufjsafyugsja12nja
    expiration-auth: 60000
    expiration-refresh: 360000
    path: /