server:
  port: 8080
auth:
  jwt:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/springdb}
      username: postgres
      password: password
  servlet:
    multipart:
      max-file-size: 1024MB
aws:
  accessKeyId: 123
  secretKey: xyz
